name: flutter_training
description: A new Flutter application.

 version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^0.1.2
  barcode_scan: ^1.0.0
  english_words: ^3.1.0
  location: ^2.3.5
  logger: ^0.6.0
  webview_flutter: ^0.3.10
  progress_indicators: ^0.1.4
  tflite: ^1.0.4
  camera: ^0.5.3
  path_provider: ^1.2.0
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
 
flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - images/

  fonts:
    - family: CustomFont
      fonts:
        - asset: fonts/samplefont.ttf

